server:
  port: 8081
  servlet:
    context-path: /luckymoney

limit:
  minMoney: 0.1
  maxMoney: 9999
  description: 最少要发一元 ${limit.minMoney}， 最多${limit.maxMoney}元
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#   时区
    url: jdbc:mysql://127.0.0.1:3307/luckymoney?serverTimezone=GMT%2B8&characterEncoding=utf-8&useUnicode=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
